name: Update Traffic Stats
on:
  schedule:
    - cron: '0 0 * * *' # Runs daily
  workflow_dispatch: # Allows manual trigger

jobs:
  update-traffic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch GitHub Traffic
        run: |
          curl -s -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/traffic/clones" > clones.json
          curl -s -H "Authorization: token ${{ secrets.SECRET_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/traffic/views" > views.json
          
          CLONES=$(jq -r '.count' clones.json)
          VIEWS=$(jq -r '.count' views.json)
          
          echo "Clones: $CLONES" >> stats.txt
          echo "Views: $VIEWS" >> stats.txt
          
          sed -i "/<!-- TRAFFIC_START -->/,/<!-- TRAFFIC_END -->/c\\
          <!-- TRAFFIC_START -->\\
          **📊 GitHub Traffic (Last 14 Days)**\\
          - Clones: $CLONES\\
          - Views: $VIEWS\\
          <!-- TRAFFIC_END -->" README.md
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Update traffic stats"
          git push
